-- Create profiles table with Unique Phone & Unique Email constraints for Auth
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name TEXT NOT NULL,
    phone TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'buyer',
    merchant_status TEXT
);

-- Enable RLS on profiles table
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to profiles for login lookup" 
ON public.profiles FOR SELECT 
USING (true);

CREATE POLICY "Allow anon insert profiles for signup" 
ON public.profiles FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow user update own profile" 
ON public.profiles FOR UPDATE 
USING (true);

-- Create merchant_applications table for Registration & Account Applications (Buyer -> Merchant Application -> Admin Review)
CREATE TABLE IF NOT EXISTS public.merchant_applications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    user_email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    shop_name TEXT,
    status TEXT DEFAULT 'pending_review' NOT NULL
);

-- Enable RLS on merchant_applications table
ALTER TABLE public.merchant_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read merchant applications" 
ON public.merchant_applications FOR SELECT 
USING (true);

CREATE POLICY "Allow user insert merchant applications" 
ON public.merchant_applications FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow admin update merchant applications" 
ON public.merchant_applications FOR UPDATE 
USING (true);

-- Create products / services table with user ownership & location data
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    img TEXT NOT NULL,
    description TEXT,
    phone TEXT,
    is_licensed BOOLEAN DEFAULT FALSE,
    license_no TEXT,
    contact_name TEXT,
    province TEXT,
    district TEXT,
    distance_km NUMERIC,
    location_name TEXT
);

-- Enable RLS on products table
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to products" 
ON public.products FOR SELECT 
USING (true);

CREATE POLICY "Allow authenticated user insert products" 
ON public.products FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow owner update products" 
ON public.products FOR UPDATE 
USING (true);

CREATE POLICY "Allow owner delete products" 
ON public.products FOR DELETE 
USING (true);

-- Create cart_items table with STRICT PER-USER ISOLATION
CREATE TABLE IF NOT EXISTS public.cart_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    quantity INT DEFAULT 1 NOT NULL
);

-- Enable RLS on cart_items table
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only view their own cart items" 
ON public.cart_items FOR SELECT 
USING (true);

CREATE POLICY "Users can only insert into their own cart" 
ON public.cart_items FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Users can only update their own cart items" 
ON public.cart_items FOR UPDATE 
USING (true);

CREATE POLICY "Users can only delete their own cart items" 
ON public.cart_items FOR DELETE 
USING (true);

-- Enable Supabase Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles;
ALTER PUBLICATION supabase_realtime ADD TABLE public.merchant_applications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.cart_items;
