-- Create products / services table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    img TEXT NOT NULL,
    description TEXT
);

-- Enable RLS on products table
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Allow public read access to products" 
ON public.products FOR SELECT 
USING (true);

CREATE POLICY "Allow anon insert products" 
ON public.products FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow anon update products" 
ON public.products FOR UPDATE 
USING (true);

CREATE POLICY "Allow anon delete products" 
ON public.products FOR DELETE 
USING (true);

-- Create cart_items table
CREATE TABLE IF NOT EXISTS public.cart_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    quantity INT DEFAULT 1 NOT NULL
);

-- Enable RLS on cart_items table
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public cart access" 
ON public.cart_items FOR ALL 
USING (true);

-- Enable Supabase Realtime for products and cart_items
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.cart_items;

-- Insert initial sample services for all 10 utility categories
INSERT INTO public.products (name, category, price, img, description) VALUES
('Cho thuê Mặt bằng Kiot Kinh doanh 50m2 Trung tâm', 'rental', 8500000, 'https://images.unsplash.com/photo-1582037928769-181f2644ecb7?w=500&q=80', 'Vị trí mặt tiền đường lớn, đông đúc cư dân, phù hợp mở shop hoặc văn phòng.'),
('Áo Sơ mi Nam Công sở Phong cách Hàn Quốc', 'fashion', 350000, 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&q=80', 'Chất liệu cotton chống nhăn, thoáng mát, phom dáng chuẩn hiện đại.'),
('Set Lẩu Thái Hải Sản & Trà Trái Cây 4 Người', 'food', 490000, 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500&q=80', 'Hải sản tươi sống kèm nước lẩu chua cay chuẩn vị, giao tận nơi trong 30 phút.'),
('Liệu trình Spa Chăm sóc Da mặt & Thải độc Chuyên sâu', 'spa', 650000, 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500&q=80', 'Tẩy tế bào chết, điện di vitamin C và massage thư giãn 75 phút.'),
('Combo Nhu yếu phẩm Gia đình Hữu cơ (Gạo, Dầu ăn, Gia vị)', 'groceries', 280000, 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=500&q=80', 'Sản phẩm đạt chứng nhận VietGAP, tươi ngon và an toàn cho sức khỏe.'),
('Dịch vụ Xe tải Vận chuyển Hàng hóa & Chuyển nhà Trọn gói', 'transport', 500000, 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=500&q=80', 'Đội ngũ xếp dỡ chuyên nghiệp, bốc xếp cẩn thận, phục vụ 24/7.'),
('Căn hộ Homestay 1 Phân khu Cao cấp đầy đủ Tiện nghi', 'lodging', 1200000, 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500&q=80', 'Đầy đủ bếp, tủ lạnh, máy giặt, hồ bơi riêng, cho thuê theo ngày hoặc tháng.'),
('Dịch vụ Bảo dưỡng Vệ sinh Máy lạnh & Sửa chữa Điện nước', 'home_services', 200000, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&q=80', 'Thợ giỏi có mặt sau 15 phút, bảo hành dịch vụ 30 ngày.'),
('Tuyển dụng Chuyên viên Tư vấn Khách hàng (Thu nhập 15-20 triệu)', 'jobs', 15000000, 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=500&q=80', 'Môi trường năng động, thưởng KPI hấp dẫn, không yêu cầu kinh nghiệm.'),
('Điểm Thu gom Pin cũ & Đổi Quà Xanh Bảo vệ Môi trường', 'public_utilities', 0, 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=500&q=80', 'Dịch vụ tiện ích cộng đồng hoàn toàn miễn phí vì không gian xanh.');
