-- Create products / services table with user ownership & location data
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    img TEXT NOT NULL,
    description TEXT,
    phone TEXT,
    is_licensed BOOLEAN DEFAULT FALSE,
    license_no TEXT,
    contact_name TEXT,
    province TEXT,
    district TEXT,
    distance_km NUMERIC,
    location_name TEXT
);

-- Enable RLS on products table
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Products RLS Policies (Public view, per-user insert/update/delete)
CREATE POLICY "Allow public read access to products" 
ON public.products FOR SELECT 
USING (true);

CREATE POLICY "Allow authenticated user insert products" 
ON public.products FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow owner update products" 
ON public.products FOR UPDATE 
USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Allow owner delete products" 
ON public.products FOR DELETE 
USING (auth.uid() = user_id OR user_id IS NULL);

-- Create cart_items table with STRICT PER-USER ISOLATION
CREATE TABLE IF NOT EXISTS public.cart_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    quantity INT DEFAULT 1 NOT NULL
);

-- Enable RLS on cart_items table for 100% per-user account isolation
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

-- Strict Cart RLS Policies (Account Isolated)
CREATE POLICY "Users can only view their own cart items" 
ON public.cart_items FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can only insert into their own cart" 
ON public.cart_items FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only update their own cart items" 
ON public.cart_items FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can only delete their own cart items" 
ON public.cart_items FOR DELETE 
USING (auth.uid() = user_id);

-- Create user_activities table for per-user history tracking
CREATE TABLE IF NOT EXISTS public.user_activities (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    action_type TEXT NOT NULL,
    details TEXT
);

-- Enable RLS on user_activities table
ALTER TABLE public.user_activities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only view their own history" 
ON public.user_activities FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can only insert their own history" 
ON public.user_activities FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Enable Supabase Realtime for products, cart_items, and user_activities
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.cart_items;
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_activities;

-- Insert initial sample services
INSERT INTO public.products (name, category, price, img, description, phone, is_licensed, license_no, contact_name, province, district, distance_km, location_name) VALUES
('Cho thuê Mặt bằng Kiot Kinh doanh 50m2 Trung tâm', 'rental', 8500000, 'https://images.unsplash.com/photo-1582037928769-181f2644ecb7?w=500&q=80', 'Vị trí mặt tiền đường lớn, đông đúc cư dân, phù hợp mở shop hoặc văn phòng.', NULL, FALSE, NULL, NULL, 'TP. Hồ Chí Minh', 'Quận 1', 0.8, 'Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh'),
('Áo Sơ mi Nam Công sở Phong cách Hàn Quốc', 'fashion', 350000, 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&q=80', 'Chất liệu cotton chống nhăn, thoáng mát, phom dáng chuẩn hiện đại.', NULL, FALSE, NULL, NULL, 'Hà Nội', 'Cầu Giấy', 1.2, 'Xuân Thủy, Cầu Giấy, Hà Nội'),
('Set Lẩu Thái Hải Sản & Trà Trái Cây 4 Người', 'food', 490000, 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500&q=80', 'Hải sản tươi sống kèm nước lẩu chua cay chuẩn vị, giao tận nơi trong 30 phút.', NULL, FALSE, NULL, NULL, 'TP. Hồ Chí Minh', 'Quận 3', 2.1, 'Lê Văn Sỹ, Quận 3, TP. Hồ Chí Minh'),
('Liệu trình Spa Chăm sóc Da mặt & Thải độc Chuyên sâu', 'spa', 650000, 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500&q=80', 'Tẩy tế bào chết, điện di vitamin C và massage thư giãn 75 phút.', NULL, FALSE, NULL, NULL, 'TP. Hồ Chí Minh', 'Quận 7', 3.5, 'Phú Mỹ Hưng, Quận 7, TP. Hồ Chí Minh'),
('Combo Nhu yếu phẩm Gia đình Hữu cơ (Gạo, Dầu ăn, Gia vị)', 'groceries', 280000, 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=500&q=80', 'Sản phẩm đạt chứng nhận VietGAP, tươi ngon và an toàn cho sức khỏe.', NULL, FALSE, NULL, NULL, 'Hà Nội', 'Nam Từ Liêm', 4.2, 'Mễ Trì, Nam Từ Liêm, Hà Nội'),
('Xe Ba Gác Chuyển Đồ Nội Khu Cư Dân (Liên hệ Trực tiếp Chủ Xe)', 'transport', 150000, 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=500&q=80', 'Danh bạ liên hệ trực tiếp chủ xe ba gác nội khu. Sàn chỉ kết nối thông tin, không thu cước hộ.', '0988.123.456', FALSE, NULL, 'Chú Hùng (Chủ xe Ba gác)', 'Hà Nội', 'Cầu Giấy', 0.5, 'Nội khu Vinhomes Cầu Giấy, Hà Nội'),
('Căn hộ Homestay OceanPark (Đã Xác Minh Giấy Phép KD)', 'lodging', 1200000, 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500&q=80', 'Cơ sở đã xác minh đủ giấy phép kinh doanh lưu trú. Gọi điện trực tiếp chủ nhà để đặt phòng.', '0912.999.888', TRUE, 'GPKD: 0108928374', 'Chị Mai (Chủ Homestay)', 'Hà Nội', 'Gia Lâm', 8.5, 'Vinhomes Ocean Park, Gia Lâm, Hà Nội'),
('Khách Sạn Sunshine Hotel & Suite (Đã Xác Minh Giấy Phép)', 'lodging', 850000, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&q=80', 'Khách sạn tiêu chuẩn 3 sao đầy đủ giấy phép PCCC & GPKD. Liên hệ hotline để đặt phòng.', '024.3829.1122', TRUE, 'GPKD: 0312984561', 'Lễ tân Sunshine Hotel', 'Hà Nội', 'Hoàn Kiếm', 1.8, 'Hàng Bông, Hoàn Kiếm, Hà Nội'),
('Dịch vụ Bảo dưỡng Vệ sinh Máy lạnh & Sửa chữa Điện nước', 'home_services', 200000, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&q=80', 'Thợ giỏi có mặt sau 15 phút, bảo hành dịch vụ 30 ngày.', NULL, FALSE, NULL, NULL, 'TP. Hồ Chí Minh', 'Quận 10', 2.8, 'Ba Tháng Hai, Quận 10, TP. Hồ Chí Minh'),
('Tuyển dụng Chuyên viên Tư vấn Khách hàng (Thu nhập 15-20 triệu)', 'jobs', 15000000, 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=500&q=80', 'Môi trường năng động, thưởng KPI hấp dẫn, không yêu cầu kinh nghiệm.', NULL, FALSE, NULL, NULL, 'TP. Hồ Chí Minh', 'TP. Thủ Đức', 6.0, 'Khu Công Nghệ Cao, TP. Thủ Đức'),
('Dịch vụ Vận tải Hàng hóa & Cẩu Thùng Thủy Nguyên', 'transport', 350000, 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=500&q=80', 'Xe cẩu thùng chở hàng hóa khu đô thị mới Thủy Nguyên. Danh bạ kết nối trực tiếp chủ xe.', '0904.555.777', FALSE, NULL, 'Nhà xe Thủy Nguyên', 'Hải Phòng', 'TP. Thủy Nguyên', 2.5, 'Trung tâm Đô thị Mới Thủy Nguyên, Hải Phòng'),
('Điểm Thu gom Pin cũ & Đổi Quà Xanh Bảo vệ Môi trường', 'public_utilities', 0, 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=500&q=80', 'Dịch vụ tiện ích cộng đồng hoàn toàn miễn phí vì không gian xanh.', NULL, FALSE, NULL, NULL, 'Hà Nội', 'Cầu Giấy', 0.9, 'Công viên Cầu Giấy, Hà Nội');
